Repository VeryGoodOpenSource/very_good_workflows, pull requests merged in 2022-10, with the labels that each got.

#73 feat: upgrade dart and flutter package to very_good_coverage@v2
  .github/workflows/dart_package.yml
  .github/workflows/flutter_package.yml
Labels: enhancement

#74 chore: v1.8.0
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: chore

#76 feat: spell check workflow
  .github/cspell.json
  .github/workflows/ci.yml
  .github/workflows/spell_check.yml
  README.md
Labels: enhancement

#65 feat(semantic_pull_request): add types and scopes inputs
  .github/workflows/ci.yml
  .github/workflows/semantic_pull_request.yml
  README.md
Labels: enhancement

#77 chore: v1.9.0
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
Labels: chore

#84 ci: add deps to scopes
  .github/workflows/ci.yml
Labels: ci

#85 feat: add optional setup step to flutter and dart package workflows
  .github/workflows/ci.yml
  .github/workflows/dart_package.yml
  .github/workflows/flutter_package.yml
  README.md
Labels: enhancement

#86 chore: v1.10.0
  CHANGELOG.md
Labels: chore
