Repository VeryGoodOpenSource/very_good_workflows, pull requests merged in 2022-07, with the labels that each got.

#52 feat(dart_package): `report_on` and `analyze_directories` inputs
  .github/workflows/dart_package.yml
  README.md
Labels: enhancement

#53 chore: v1.5.0
  CHANGELOG.md
Labels: chore

#54 fix(semantic_pull_request): remove wip (write access)
  .github/workflows/semantic_pull_request.yml
Labels: bug

#55 chore: v1.5.1
  CHANGELOG.md
Labels: chore

#57 feat(dart_package): add runs_on input
  .github/workflows/dart_package.yml
  README.md
Labels: enhancement

#58 chore: v1.5.2
  CHANGELOG.md
Labels: chore

#59 feat(flutter_package): add runs_on input
  .github/workflows/flutter_package.yml
  README.md
Labels: enhancement

#60 chore: v1.5.3
  CHANGELOG.md
Labels: chore
